export interface MakeEntry {
  make: string;
  models: string[];
}

// ─── Years ────────────────────────────────────

export const YEARS = Array.from({ length: 2026 - 1920 + 1 }, (_, i) => (1920 + i).toString());

// ─── Colors ───────────────────────────────────

export const EXTERIOR_COLORS = [
  "Black", "White", "Silver", "Gray", "Charcoal",
  "Red", "Maroon", "Burgundy", "Candy Red",
  "Blue", "Navy", "Royal Blue", "Sky Blue", "Baby Blue", "Albert Blue",
  "Green", "British Racing Green", "Dark Green", "Olive", "Teal",
  "Yellow", "Gold", "Cream", "Beige",
  "Brown", "Tan", "Saddle", "Champagne",
  "Orange", "Copper", "Bronze",
  "Purple", "Plum", "Lavender",
  "Pink", "Rose",
  "Metallic", "Matte Black", "Matte Gray",
  "Two-Tone", "Other",
];

export const INTERIOR_COLORS = [
  "Black", "Charcoal", "Gray", "Silver",
  "Beige", "Tan", "Brown", "Saddle", "Cognac",
  "Red", "Burgundy", "Maroon", "Bordeaux",
  "Blue", "Navy", "Dark Blue",
  "Green", "Dark Green",
  "Cream", "Ivory", "White",
  "Yellow", "Gold",
  "Orange",
  "Two-Tone", "Other",
];

export const TRANSMISSIONS = ["Manual", "Automatic", "Other"];

// ─── Countries ────────────────────────────────

export const COUNTRIES = [
  "Egypt", "United Arab Emirates", "Saudi Arabia", "Qatar", "Kuwait",
  "Bahrain", "Oman", "Jordan", "Lebanon", "Palestine", "Iraq", "Syria", "Yemen",
  "United States", "Canada", "Mexico",
  "United Kingdom", "Germany", "France", "Italy", "Spain", "Portugal",
  "Netherlands", "Belgium", "Switzerland", "Austria", "Sweden", "Norway",
  "Denmark", "Finland", "Ireland", "Poland", "Czech Republic", "Greece",
  "Turkey", "Russia", "Ukraine", "Romania", "Hungary",
  "Japan", "South Korea", "China", "India", "Thailand", "Indonesia", "Philippines",
  "Australia", "New Zealand",
  "South Africa", "Morocco", "Algeria", "Tunisia", "Nigeria", "Kenya", "Ghana",
  "Brazil", "Argentina", "Chile", "Colombia", "Peru", "Venezuela",
  "Other",
];

// ─── Car Makes & Models ───────────────────────

export const MAKES: MakeEntry[] = [
  { make: "Acura", models: ['Integra', 'Legend', 'NSX', 'TL', 'CL', 'RL', 'TSX', 'RSX', 'MDX', 'RDX', 'ZDX', 'TLX', 'ILX', 'RLX', 'NSX Type S', 'Integra Type S', 'ADX'] },
  { make: "Alfa Romeo", models: ['Giulia', 'Giulietta', 'Spider', 'GTV', '156', '147', '159', 'Brera', 'MiTo', '4C', 'Stelvio', 'Tonale', '8C Competizione', 'Montreal', '33 Stradale', 'Giulia Quadrifoglio', 'Alfetta', '75/Milano', '164', 'GT', 'GTA'] },
  { make: "Aston Martin", models: ['DB5', 'DB6', 'DBS', 'V8 Vantage', 'Virage', 'DB7', 'Vanquish', 'DB9', 'V8 Vantage (2005)', 'DBS Superleggera', 'One-77', 'Rapide', 'Valkyrie', 'DB11', 'Vantage (2018)', 'DBS (2018)', 'DBX', 'DB12', 'Valhalla', 'Vanquish (2024)', 'Valour', 'DB5 Vantage'] },
  { make: "Audi", models: ['80', '100', '200', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'Q4 e-tron', 'Q6 e-tron', 'TT', 'R8', 'S3', 'S4', 'S5', 'S6', 'S7', 'S8', 'RS3', 'RS4', 'RS5', 'RS6', 'RS7', 'RS Q8', 'Quattro', 'Sport Quattro', 'V8', 'Cabriolet', 'A2', 'A1', 'Q2', 'RS2 Avant', 'e-tron GT', 'RS e-tron GT'] },
  { make: "Bentley", models: ['3 Litre', 'Speed Six', '8 Litre', '4½ Litre', 'R Type', 'Continental', 'S1/S2/S3', 'T Series', 'Mulsanne', 'Turbo R', 'Continental R/T', 'Arnage', 'Azure', 'Continental GT', 'Continental Flying Spur', 'Bentayga', 'Flying Spur', 'Continental GTC', 'Mulsanne (2010)', 'Bacalar', 'Batur'] },
  { make: "BMW", models: ['3 Series', '5 Series', '7 Series', '1 Series', '2 Series', '4 Series', '6 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z3', 'Z4', 'Z8', 'i3', 'i8', 'iX', 'i4', 'i7', 'iX3', 'M3', 'M4', 'M5', 'M6', 'M8', 'X3 M', 'X5 M', 'X6 M', 'M2', 'M1', '2002', 'E30 M3', 'E28 M5', 'E39 M5', 'E46 M3', '1M Coupe', 'M760Li', 'XM', 'Neue Klasse', 'Isetta', '507', '328', '3.0 CSL'] },
  { make: "Buick", models: ['LeSabre', 'Electra', 'Park Avenue', 'Roadmaster', 'Riviera', 'Century', 'Regal', 'LaCrosse', 'Lucerne', 'Enclave', 'Encore', 'Envision', 'Verano', 'Skylark', 'Special', 'Wildcat', 'Reatta', 'Lesabre', 'Apollo', 'Opel', 'GSX', 'Grand National', 'GNX', 'Electra 225', 'Encore GX', 'Envista', 'Electra E5'] },
  { make: "Cadillac", models: ['DeVille', 'Fleetwood', 'Eldorado', 'Seville', 'Catera', 'CTS', 'DTS', 'STS', 'XLR', 'SRX', 'Escalade', 'ATS', 'CT6', 'XT5', 'XT4', 'XT6', 'CT4', 'CT5', 'Celestiq', 'Lyriq', 'Optiq', 'Escalade IQ', 'V-16', 'Sixty Special', 'Brougham', 'Allanté', 'Cimarron', 'CT4-V', 'CT5-V', 'Blackwing'] },
  { make: "Chevrolet", models: ['Camaro', 'Corvette', 'Impala', 'Malibu', 'Cruze', 'Equinox', 'Tahoe', 'Suburban', 'Silverado', 'Colorado', 'Traverse', 'Trailblazer', 'Blazer', 'Spark', 'Sonic', 'Aveo', 'Cavalier', 'Lumina', 'Monte Carlo', 'Caprice', 'Bel Air', 'Nova', 'Chevelle', 'El Camino', 'Vega', 'Cobalt', 'HHR', 'Trax', 'Bolt EV', 'Bolt EUV', 'Silverado EV', 'Blazer EV', 'Equinox EV', 'Corvette Stingray', 'Corvette Z06', 'Corvette ZR1', 'SS', 'SSR', 'Astro', 'Express', 'Venture', 'Uplander', 'Beretta', 'Corsica', 'Celebrity', 'Citation'] },
  { make: "Chrysler", models: ['300', '300C', '300M', 'Concorde', 'LHS', 'New Yorker', 'Town & Country', 'Voyager', 'Pacifica', 'PT Cruiser', 'Sebring', 'Cirrus', 'LeBaron', 'Fifth Avenue', 'Imperial', 'Crossfire', 'Aspen', 'Airflow', 'Cordoba', 'Valiant', 'Daytona', 'Laser', 'TC by Maserati', 'Pacifica Hybrid', '300 (2026)'] },
  { make: "Citroën", models: ['2CV', 'DS', 'ID', 'CX', 'BX', 'XM', 'ZX', 'Saxo', 'AX', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C8', 'Picasso', 'C3 Picasso', 'C4 Picasso', 'Grand C4 Picasso', 'Berlingo', 'Jumpy', 'Jumper', 'C4 Cactus', 'C3 Aircross', 'C5 Aircross', 'C-Elysée', 'DS3', 'DS4', 'DS5', 'Ami', 'Traction Avant', 'SM', 'Mehari', 'Dyane', 'Ami (2020)', 'C3 (2024)', 'Basalt'] },
  { make: "Dacia", models: ['1300', '1310', 'Denem', 'Solenza', 'SupeRNova', 'Logan', 'Sandero', 'Duster', 'Lodgy', 'Dokker', 'Stepway', 'Jogger', 'Spring', 'Bigster', '1302', '1304 Pick-Up', '1410', 'Nova'] },
  { make: "Daewoo", models: ['Tico', 'Lanos', 'Nubira', 'Leganza', 'Matiz', 'Kalos', 'Lacetti', 'Magnus', 'Evanda', 'Statesman', 'Chairman', 'Espero', 'Damas', 'Labo', 'Tacuma', 'Winstorm', 'Tosca', 'G2X'] },
  { make: "Daihatsu", models: ['Charade', 'Mira', 'Cuore', 'Sirion', 'Terios', 'Rocky', 'Feroza', 'Applause', 'Move', 'Tanto', 'Copen', 'Materia', 'Boon', 'Hijet', 'Atrai', 'Gran Move', 'Opti', 'Leeza', 'YRV', 'Trevis', 'Cast', 'Wake', 'Thor', 'Rugger', 'Taft'] },
  { make: "Dodge", models: ['Charger', 'Challenger', 'Durango', 'Grand Caravan', 'Viper', 'Neon', 'Avenger', 'Stratus', 'Intrepid', 'Dart', 'Caliber', 'Magnum', 'Ram', 'Dakota', 'Durango', 'Journey', 'Nitro', 'Stealth', 'Daytona', 'Omni', 'Aries', 'Diplomat', 'Monaco', 'Coronet', 'Polara', 'Dart (2013)', 'Hornet', 'Hemi', 'Power Wagon', 'Charger Daytona EV', 'Challenger SRT Demon', 'Viper ACR', 'Lancer', 'Colt', 'Raider', 'Spirit', 'Shadow'] },
  { make: "Ferrari", models: ['250 GT', '250 GTO', '275 GTB', '330', '365', 'Dino 246', 'Testarossa', 'F40', 'F50', 'Enzo', 'LaFerrari', '308 GTB', '328', '348', '355', '360 Modena', '430', '458 Italia', '488 GTB', 'F8 Tributo', 'SF90 Stradale', '296 GTB', 'Roma', 'Portofino', 'California', 'FF', 'GTC4Lusso', 'Purosangue', '12Cilindri', 'F80', 'Monza SP1/SP2', 'Daytona SP3', '512 BBi', 'Mondial', '400', '412', 'F12berlinetta', '812 Superfast', '599 GTB'] },
  { make: "Fiat", models: ['500', 'Panda', 'Punto', 'Bravo', 'Brava', 'Stilo', 'Palio', 'Siena', 'Uno', 'Cinquecento', 'Seicento', 'Tipo', 'Tempra', 'Croma', 'Regata', 'Ritmo', 'Strada', '131', '124', '126', '127', '128', 'X1/9', 'Barchetta', 'Coupe', 'Dino', 'Spider', '124 Spider', 'Multipla', 'Idea', 'Linea', 'Doblo', 'Fiorino', 'Ducato', 'Scudo', 'Panda 4x4', '500X', '500L', '500C', '500e', 'Pulse', 'Fastback', 'Grande Panda', 'Topolino', '850', '600', '1100', '1500'] },
  { make: "Ford", models: ['Model T', 'Model A', 'Mustang', 'F-150', 'F-250', 'F-350', 'Bronco', 'Explorer', 'Expedition', 'Escape', 'Edge', 'Focus', 'Fiesta', 'Fusion', 'Taurus', 'Thunderbird', 'Galaxie', 'Fairlane', 'Torino', 'Pinto', 'Maverick', 'Ranger', 'Transit', 'E-Series', 'Crown Victoria', 'Gran Torino', 'Escort', 'Contour', 'Tempo', 'Probe', 'Windstar', 'Aerostar', 'Mustang Mach-E', 'Bronco Sport', 'Maverick (2022)', 'GT', 'GT40', 'GT (2017)', 'Sierra', 'Scorpio', 'Granada', 'Capri', 'LTD', 'Country Squire', 'F-150 Lightning', 'Transit Connect', 'Flex', 'Taunus', 'Consul', 'Zephyr', 'Anglia', 'Prefect'] },
  { make: "Genesis", models: ['G70', 'G80', 'G90', 'GV60', 'GV70', 'GV80', 'GV80 Coupe', 'Electrified G80', 'Genesis Coupe', 'Genesis Sedan (BH)', 'Mint Concept', 'Neolun', 'GV60 Magma'] },
  { make: "GMC", models: ['Sierra', 'Sierra HD', 'Yukon', 'Yukon XL', 'Acadia', 'Terrain', 'Canyon', 'Savana', 'Jimmy', 'Suburban', 'Vandura', 'Sonoma', 'Safari', 'Envoy', 'Syclone', 'Typhoon', 'Hummer EV (rebadged)', 'C/K Series', 'Hummer', 'TopKick', 'T-6500', 'Sierra EV', 'Hummer EV SUV', 'Hummer EV Pickup'] },
  { make: "Honda", models: ['Civic', 'Accord', 'CR-V', 'Pilot', 'Odyssey', 'Fit/Jazz', 'City', 'Insight', 'Ridgeline', 'Passport', 'HR-V', 'Element', 'CR-Z', 'S2000', 'NSX', 'Prelude', 'Integra', 'Del Sol', 'Beat', 'S660', 'Legend', 'Clarity', 'CRX', 'Crosstour', 'N600', 'Z600', 'Vigor', 'Vamos', 'Acty', 'FR-V', 'Stream', 'Shuttle', 'Avancier', 'Prologue', 'Prologue (2026)', 'ZR-V', 'Elevate', 'Step WGN', 'N-Box', 'N-One', 'N-Van', 'N-WGN', 'Mobilio', 'Life', 'Today', 'Zest'] },
  { make: "Hummer", models: ['H1', 'H2', 'H3', 'H3T', 'Hummer EV Pickup', 'Hummer EV SUV'] },
  { make: "Hyundai", models: ['Elantra', 'Sonata', 'Accent', 'Tucson', 'Santa Fe', 'Palisade', 'Kona', 'Venue', 'Ioniq 5', 'Ioniq 6', 'Ioniq', 'Nexo', 'Veloster', 'Genesis Coupe', 'Azera', 'Equus', 'Genesis', 'Tiburon', 'Coupe', 'Santa Cruz', 'Staria', 'Porter', 'i10', 'i20', 'i30', 'i40', 'ix20', 'ix35', 'Getz', 'Atos', 'Pony', 'Stellar', 'Grandeur', 'Dynasty', 'Excel', 'Scoupe', 'XG', 'Kona Electric', 'IONIQ 5 N', 'IONIQ 9', 'Casper', 'Bayon', 'Mighty', 'County'] },
  { make: "Infiniti", models: ['Q45', 'G20', 'G35', 'G37', 'M30', 'M35', 'M45', 'FX35', 'FX45', 'FX50', 'QX4', 'QX56', 'J30', 'I30', 'I35', 'EX35', 'EX37', 'QX50', 'QX60', 'QX70', 'QX80', 'Q50', 'Q60', 'Q70', 'Q30', 'QX30', 'Q40', 'Q70L', 'QX55', 'QX50 (2024)', 'Q60 Black S'] },
  { make: "Isuzu", models: ['Trooper', 'Rodeo', 'Amigo', 'VehiCROSS', 'Axiom', 'Ascender', 'Hombre', 'i-Series', 'MU-7', 'D-Max', 'KB', 'N-Series', 'F-Series', 'Gemini', 'Impulse', 'Stylus', 'Piazza', '117 Coupe', 'Florian', 'Bellett', 'Minx', 'MU-X', 'Traviz'] },
  { make: "Jaguar", models: ['E-Type', 'XK120', 'XK140', 'XK150', 'MK2', 'Mark VII', 'Mark VIII', 'Mark IX', 'XJ6', 'XJ12', 'XJ8', 'XJ', 'XJS', 'XK8', 'XKR', 'S-Type', 'X-Type', 'XF', 'XE', 'F-Type', 'F-Pace', 'E-Pace', 'I-Pace', 'C-Type', 'D-Type', 'XJR', 'XJR-15', 'XJ220', 'C-X75', 'Mark V', 'SS 100', '420', '240', '340'] },
  { make: "Jeep", models: ['Wrangler', 'Cherokee', 'Grand Cherokee', 'Compass', 'Renegade', 'Patriot', 'Liberty', 'Commander', 'Wagoneer', 'Grand Wagoneer', 'Gladiator', 'CJ', 'CJ-5', 'CJ-7', 'YJ', 'TJ', 'JK', 'JL', 'XJ Cherokee', 'ZJ', 'WJ', 'WK', 'WK2', 'Willys', 'Jeepster', 'FC', 'Gladiator (JT)', 'Comanche', 'Scrambler', 'DJ', 'M715', 'Wagoneer S', 'Avenger', 'Recon', 'Grand Cherokee L'] },
  { make: "Kia", models: ['Optima', 'Sorento', 'Sportage', 'Soul', 'Forte', 'Rio', 'Cerato', 'Ceed', 'Picanto', 'Stinger', 'Telluride', 'Sedona', 'Carnival', 'Seltos', 'Niro', 'EV6', 'EV9', 'K5', 'K7', 'K9', 'Mohave', 'Borrego', 'Amanti', 'Rondo', 'Mentor', 'Pride', 'Sephia', 'Spectra', 'Shuma', 'Magentis', 'Lotze', 'Opirus', 'Venga', 'ProCeed', 'XCeed', 'EV3', 'EV4', 'EV5', 'Tasman', 'Syros', 'Ray'] },
  { make: "Lamborghini", models: ['350 GT', '400 GT', 'Miura', 'Countach', 'Urraco', 'Jalpa', 'Silhouette', 'LM002', 'Diablo', 'Murciélago', 'Gallardo', 'Reventón', 'Aventador', 'Huracán', 'Urus', 'Revuelto', 'Temerario', 'Sesto Elemento', 'Veneno', 'Centenario', 'Sián', 'Countach LPI 800-4', 'Lanzador', 'Espada', 'Islero', 'Jarama', 'Asterion'] },
  { make: "Lancia", models: ['Delta', 'Delta Integrale', 'Stratos', 'Aurelia', 'Flaminia', 'Fulvia', 'Beta', 'Gamma', 'Thema', 'Thesis', 'Lybra', 'Kappa', 'Y10', 'Ypsilon', 'Musa', 'Phedra', 'Zeta', 'Dedra', 'Prisma', 'Trevi', '037 Rally', 'LC2', 'Aprilia', 'Ardea', 'Appia', 'Lambda', 'Flavia', 'Ypsilon (2024)', 'Voyager', 'Flaminia', 'Montecarlo/Scorpion'] },
  { make: "Land Rover", models: ['Series I', 'Series II', 'Series III', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar', 'Range Rover SV', 'Discovery', 'Discovery Sport', 'Freelander', 'Defender', 'Defender 90', 'Defender 110', 'Defender 130', 'LR2', 'LR3', 'LR4', 'Range Rover Classic', 'Range Rover P38', 'Range Rover L322', 'Range Rover L405', 'Range Rover L460', 'Defender (L663)', 'Discovery Series II'] },
  { make: "Lexus", models: ['LS', 'ES', 'GS', 'IS', 'LC', 'RC', 'NX', 'RX', 'GX', 'LX', 'UX', 'SC', 'HS', 'CT', 'LFA', 'RZ', 'TX', 'LM', 'LBX', 'RZ 450e', 'LX 600', 'GX 550', 'IS F', 'RC F', 'GS F', 'LC 500', 'LC 500h', 'RX 350', 'RX 450h', 'RX 500h', 'NX 350h', 'NX 450h+', 'ES 300h', 'LS 500', 'LS 500h', 'LFA Nürburgring', 'SC 300', 'SC 400', 'SC 430'] },
  { make: "Lincoln", models: ['Continental', 'Town Car', 'Mark IV', 'Mark V', 'Mark VII', 'Mark VIII', 'LS', 'Zephyr', 'MKZ', 'MKS', 'MKT', 'MKC', 'MKS', 'Navigator', 'Aviator', 'Corsair', 'Nautilus', 'Blackwood', 'Premiere', 'Capri', 'Versailles', 'Model L', 'Model K', 'Model KA', 'Custom', 'Cosmopolitan', 'Capri', 'Mark LT', 'Town Car (2011)', 'Continental (2017)', 'Nautilus (2024)', 'Navigator L', 'Aviator Grand Touring'] },
  { make: "Lotus", models: ['Seven', 'Elan', 'Esprit', 'Elite', 'Eclat', 'Excel', 'Elise', 'Exige', 'Evora', 'Emira', 'Eletre', 'Emeya', 'Europa', 'Cortina', 'Carlton', '340R', '2-Eleven', '3-Eleven', 'Evija', 'Esprit Turbo', 'Esprit V8', 'Elan +2', 'Eleven', 'Mark VI', 'Mark VIII', 'Type 49', 'Type 72', 'Type 79', 'Type 99T'] },
  { make: "Maserati", models: ['A6', '3500 GT', 'Mistral', 'Ghibli', 'Indy', 'Bora', 'Merak', 'Khamsin', 'Kyalami', 'Quattroporte', 'Biturbo', '228', '430', 'Shamal', 'Ghibli II', '3200 GT', 'Coupé', 'Spyder', 'GranTurismo', 'GranCabrio', 'Quattroporte V', 'Quattroporte VI', 'Ghibli (2013)', 'Levante', 'MC20', 'Grecale', 'MC12', 'MC20 Cielo', 'Folgore', 'Birdcage 75th', 'Boomerang', 'A6GCS', '150S', 'Tipo 61 Birdcage', 'Alfieri', 'GranTurismo Folgore'] },
  { make: "Mazda", models: ['MX-5 Miata', 'RX-7', 'RX-8', 'Cosmo Sport', 'Mazda3', 'Mazda6', 'CX-3', 'CX-5', 'CX-7', 'CX-9', 'CX-30', 'CX-50', 'CX-70', 'CX-90', 'BT-50', 'MPV', '5', '2', '121', '626', '929', '323', 'Familia', 'Capella', 'Luce', 'Carol', 'AZ-1', 'Autozam', 'Eunos Roadster', 'Xedos 6', 'Xedos 9', 'MX-3', 'MX-6', 'Millenia', 'Protegé', 'Tribute', 'Navajo', 'B-Series', 'R360', 'K360', 'T1500', 'Bongo', 'Spiano', 'Sentia', 'Etude', 'Lantis', 'MX-30', 'CX-90 PHEV', 'Mazda3 Turbo', 'MX-5 RF', 'RX-Vision', 'ICONIC SP'] },
  { make: "McLaren", models: ['F1', 'Mercedes-Benz SLR McLaren', 'MP4-12C', '650S', '675LT', '720S', '750S', 'P1', 'P1 GTR', 'Senna', 'Senna GTR', 'Speedtail', 'Elva', '765LT', 'Artura', 'GTS', 'W1', 'Solus GT', '600LT', '570S', '570GT', '540C', 'GT', 'Sabre', '765LT Spider', 'Artura Spider', 'P1 LM'] },
  { make: "Mercedes-Benz", models: ['A-Class', 'B-Class', 'C-Class', 'E-Class', 'S-Class', 'CLK', 'CLS', 'CLA', 'CL', 'SL', 'SLC', 'SLK', 'SLS AMG', 'AMG GT', 'G-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'GL', 'M-Class', 'ML', 'R-Class', 'V-Class', 'Vito', 'Sprinter', 'EQC', 'EQS', 'EQE', 'EQB', 'EQA', 'EQV', 'EQS SUV', 'EQE SUV', 'Maybach S-Class', '300 SL Gullwing', '190SL', '280SL', '600 Grosser', 'W123', 'W124', 'W201 190E', 'C111', '300D', '450SEL 6.9', '190E 2.3-16', '500E', 'C63 AMG', 'E63 AMG', 'S65 AMG', 'G63 AMG', 'AMG One', '300 SEL', '220', '170V', 'W114/W115', 'W108', 'W116', 'W126', 'W140', 'W220', 'W221', 'W222', 'W223', 'SL Pagoda', 'SL R129', 'SL R230', 'SL R231'] },
  { make: "Mercury", models: ['Cougar', 'Marquis', 'Grand Marquis', 'Sable', 'Topaz', 'Lynx', 'Capri', 'Montego', 'Milan', 'Mountaineer', 'Mariner', 'Mystique', 'Mercury', 'Eight', 'Montclair', 'Park Lane', 'Monterey', 'Colony Park', 'Voyager', 'Comet', 'Cyclone', 'Marauder', 'Zephyr', 'Tracer', 'Villager', 'Milan (2006)', 'Mariner Hybrid', 'Grand Marquis LS'] },
  { make: "MG", models: ['MGA', 'MGB', 'MGC', 'Midget', 'Magnette', 'TD', 'TF', 'TC', 'YA', 'ZA', 'RV8', 'F', 'TF (2002)', 'ZR', 'ZS', 'ZT', 'MG3', 'MG5', 'MG6', 'MG7', 'HS', 'ZS EV', 'MG4 EV', 'Cyberster', 'Gloster', 'Hector', 'Astor', 'RX8', 'Winsor', 'Maxus 90', 'MG9', 'EX4', 'XPower', 'MG6 XPOWER', 'MGB GT V8', 'Metro', 'Maestro', 'Montego'] },
  { make: "Mini", models: ['Mini (1959)', 'Mini Clubman', 'Mini Countryman', 'Mini Cooper', 'Mini Cooper S', 'Mini John Cooper Works', 'Mini One', 'Mini Hatch', 'Mini Cabrio', 'Mini Paceman', 'Mini Coupe', 'Mini Roadster', 'Mini Electric', 'Mini Aceman', 'Mini Cooper (1994)', 'Mini (2014)', 'Mini Countryman EV', 'Mini John Cooper Works GP', 'Mini Clubvan', 'Mini Beachcomber'] },
  { make: "Mitsubishi", models: ['Lancer', 'Lancer Evolution', 'Galant', 'Colt', 'Mirage', 'Space Star', 'Pajero', 'Montero', 'Outlander', 'Eclipse', 'Eclipse Cross', 'ASX', 'RVR', 'Delica', '3000GT', 'GTO', 'Starion', 'Sigma', 'Diamante', 'Debonair', 'Pajero Sport', 'Shogun', 'Triton', 'L200', 'Mighty Max', 'i-MiEV', 'Minicab', 'FTO', 'Chariot', 'Space Runner', 'Space Wagon', 'Lancer EX', 'Cordia', 'Tredia', 'Precis', 'Raider', 'Xpander', 'Xforce', 'Pajero Mini', 'Minica', 'Town Box', 'eK Series', 'Pajero Evolution'] },
  { make: "Nissan", models: ['Altima', 'Sentra', 'Maxima', 'Versa', 'Murano', 'Rogue', 'Pathfinder', 'Armada', 'Frontier', 'Titan', '370Z', 'Z (400Z)', 'GT-R', 'Leaf', 'Ariya', 'Juke', 'Kicks', 'Qashqai', 'X-Trail', 'Note', 'Micra', 'Pulsar', 'Sunny', 'Skyline', 'Silvia', '180SX', '200SX', '240SX', '300ZX', 'Fairlady Z', 'Datsun 510', 'Datsun 240Z', 'Bluebird', 'Cedric', 'Gloria', 'President', 'Pathfinder Armada', 'Quest', 'Cube', 'Serena', 'Elgrand', 'Navara', 'Patrol', 'Tino', 'Almera', 'Primera', 'Stanza', 'NX Coupe', 'NX 1600', '2000 GT-R', 'Skyline GT-R', 'R32', 'R33', 'R34', 'Stagea', 'Cima', 'Fuga', 'Infiniti Q45 (rebadge)', 'Magnite', 'Terrano', 'Datsun Redi-Go', 'Hypermini', 'Prairie', 'Bassara'] },
  { make: "Oldsmobile", models: ['Cutlass', 'Cutlass Supreme', 'Cutlass Ciera', '88', '98', 'Toronado', 'Starfire', 'Alero', 'Aurora', 'Intrigue', 'Silhouette', 'Bravada', 'Achieva', 'Calais', 'Omega', 'Delta 88', 'Ninety-Eight', 'Vista Cruiser', 'F-85', 'Jetfire', '442', 'Rallye 350', 'Holiday', 'Dynamic 88', 'Super 88', 'Firenza', 'Custom Cruiser', 'LSS', 'Regency', 'Touring Sedan', '442 (1970)'] },
  { make: "Opel", models: ['Kadett', 'Ascona', 'Manta', 'Rekord', 'Commodore', 'Diplomat', 'Senator', 'Monza', 'Omega', 'Vectra', 'Calibra', 'Corsa', 'Astra', 'Insignia', 'Zafira', 'Meriva', 'Agila', 'Tigra', 'Speedster', 'GT', 'Adam', 'Karl', 'Crossland', 'Grandland', 'Mokka', 'Combo', 'Vivaro', 'Movano', 'Frontera', 'Monterey', 'Campo', 'Sintra', 'Signum', 'Ampera', 'Ampera-e', 'Rocks-e', 'Corsa-e', 'Mokka-e', 'Astra-e', 'Grandland', 'Frontera (2024)', 'Olympia', 'P4', 'Kapitan', 'Blitz', 'GT (1968)', 'GT (2007)', '1900', 'Super Six'] },
  { make: "Peugeot", models: ['201', '202', '203', '204', '205', '206', '207', '208', '301', '302', '304', '305', '306', '307', '308', '309', '401', '402', '403', '404', '405', '406', '407', '408', '504', '505', '508', '601', '604', '605', '607', '806', '807', '1007', '2008', '3008', '4007', '4008', '5008', 'RCZ', 'Rifter', 'Traveller', 'Boxer', 'Expert', 'Partner', 'Bipper', 'iOn', 'e-208', 'e-2008', 'e-3008', 'e-308', 'e-408', 'e-5008', 'Peugeot 9X8', '504 Coupe', '504 Cabriolet', '205 GTI', '205 T16', '206 WRC', '106', '107', '108', '301 (2012)', '408 (2025)', 'Landtrek', '508 PSE'] },
  { make: "Plymouth", models: ['Barracuda', 'Road Runner', 'GTX', 'Satellite', 'Belvedere', 'Fury', 'Valiant', 'Duster', 'Horizon', 'Reliant', 'Gran Fury', 'Volare', 'Acclaim', 'Sundance', 'Neon', 'Prowler', 'Breeze', 'Voyager', 'Grand Voyager', 'Cranbrook', 'Cambridge', 'Savoy', 'Plaza', 'Suburban', 'Special Deluxe', 'Superbird', 'Cuda', 'Sport Fury', 'Trail Duster', 'Arrow', 'Champ', 'Plymouth (1928)', 'Model Q', 'Model 30'] },
  { make: "Pontiac", models: ['GTO', 'Firebird', 'Trans Am', 'Grand Prix', 'LeMans', 'Tempest', 'Catalina', 'Bonneville', 'Parisienne', 'Grand Am', 'Sunfire', 'Sunbird', 'Phoenix', 'Ventura', '6000', 'Fiero', 'Acadian', 'Beaumont', 'Strato Chief', 'Grand Safari', 'Safari', 'Laurentian', 'Aztek', 'Montana', 'Solstice', 'Vibe', 'G5', 'G6', 'G8', 'Torrent', 'Chieftain', 'Silver Streak', 'Streamliner', 'Banshee', 'GTO (2004)', 'G8 GXP', 'Fiero GT', 'Trans Am WS6', 'Firebird Formula'] },
  { make: "Porsche", models: ['356', '911', '912', '914', '924', '928', '944', '968', 'Boxster', 'Cayman', 'Panamera', 'Macan', 'Cayenne', 'Taycan', 'Carrera GT', '918 Spyder', '959', '911 Turbo', '911 GT3', '911 GT2 RS', '911 Carrera RS', '911 Targa', '911 Speedster', 'Cayman GT4', '718 Boxster', '718 Cayman', '911 Dakar', '911 S/T', '911 R', '550 Spyder', '356 Speedster', '911 GT1', 'Mission E', 'Taycan Cross Turismo', 'Macan EV', '911 GT3 RS (992)', '961', 'Cayenne Coupé', 'Panamera Sport Turismo'] },
  { make: "Ram", models: ['Ram 1500', 'Ram 2500', 'Ram 3500', 'Ram 4500', 'Ram 5500', 'Ram ProMaster', 'Ram ProMaster City', 'Ram 1500 Classic', 'Ram 1500 TRX', 'Ram 1500 RHO', 'Ram 1500 REV', 'Ramcharger', 'Ram Daytona', 'Ram Sport', 'Ram Laramie', 'Ram Longhorn', 'Ram Limited', 'Ram Rebel', 'Ram 700'] },
  { make: "Renault", models: ['R4', 'R5', 'R6', 'R8', 'R10', 'R12', 'R14', 'R15', 'R16', 'R17', 'R18', 'R19', 'R20', 'R21', 'R25', 'R30', 'Clio', 'Mégane', 'Laguna', 'Safrane', 'Avantime', 'Vel Satis', 'Twingo', 'Modus', 'Wind', 'Zoe', 'Kangoo', 'Trafic', 'Master', 'Espace', 'Scénic', 'Grand Scénic', 'Koleos', 'Kadjar', 'Captur', 'Talisman', 'Latitude', 'Fluence', 'Arkana', 'Austral', 'Rafale', 'Symbioz', '5 E-Tech', 'Scénic E-Tech', 'R4 E-Tech', 'Mégane E-Tech', 'Suzuki (collaboration)', 'Twizy', 'City K-ZE', 'Kwid', 'Triber', 'Kiger', 'Duster Oroch', 'Logan', 'Sandero', 'Alpine A110', 'Alpine A310', 'Alpine A610', 'Renault Sport Spider', 'Clio V6', 'R5 Turbo', 'R5 Turbo 2', 'Maxi 5 Turbo'] },
  { make: "Rolls-Royce", models: ['Silver Ghost', 'Phantom I', 'Phantom II', 'Phantom III', 'Silver Cloud', 'Silver Shadow', 'Silver Spur', 'Silver Wraith', 'Corniche', 'Camargue', 'Silver Seraph', 'Park Ward', 'Phantom (2003)', 'Phantom Drophead Coupé', 'Phantom Coupé', 'Ghost', 'Wraith', 'Dawn', 'Cullinan', 'Spectre', 'Boat Tail', 'Sweptail', 'Droptail', 'Silver Dawn', 'Bentley (shared era)', 'Phantom VIII', 'Ghost Series II', 'Black Badge', 'Cullinan Series II'] },
  { make: "Rover", models: ['P4', 'P5', 'P6', 'SD1', '200', '400', '600', '800', '25', '45', '75', 'Streetwise', 'CityRover', 'Metro', 'Mini (Rover era)', 'Maestro', 'Montego', 'Quintet', 'Vitesse', 'Land Rover (original)', 'Rover 100', 'Rover 200 (1984)', 'Rover 800 (1986)', 'Rover 75 Tourer', 'Rover 75 V8'] },
  { make: "Saab", models: ['92', '93', '95', '96', '97 Sonett', '99', '900', '90', '9000', '9-3', '9-5', '9-2X', '9-4X', '9-7X', 'Sonett I', 'Sonett II', 'Sonett III', '99 Turbo', '900 Turbo', '9000 Turbo', '9-3 Aero', '9-5 Aero', '9-3 SportCombi', '9-3 Convertible', '9-5 NG', 'PhoeniX'] },
  { make: "Saturn", models: ['S-Series', 'SL', 'SC', 'SW', 'Ion', 'Vue', 'L-Series', 'L100', 'L200', 'L300', 'Relay', 'Aura', 'Outlook', 'Sky', 'Astra (rebadged)', 'Saturn EV1'] },
  { make: "Seat", models: ['600', '850', '124', '127', '128', '131', 'Ibiza', 'Malaga', 'Ronda', 'Marbella', 'Toledo', 'Leon', 'Cordoba', 'Arosa', 'Alhambra', 'Altea', 'Altea XL', 'Altea Freetrack', 'Exeo', 'Mii', 'Ateca', 'Arona', 'Tarraco', 'Cupra (brand split)', 'Leon Cupra', 'Ibiza Cupra', '600 D', 'Trans', 'Terra', 'Inca', 'Cupra Formentor', 'Cupra Born', 'Cupra Leon', 'Cupra Ateca', 'Cupra Tavascan', 'Cupra Terramar'] },
  { make: "Škoda", models: ['Octavia', 'Superb', 'Fabia', 'Rapid', 'Roomster', 'Yeti', 'Kodiaq', 'Karoq', 'Kamiq', 'Enyaq iV', 'Enyaq Coupé iV', 'Citigo', 'Citigo-e iV', 'Scala', 'Felicia', 'Favorit', 'Forman', 'Pick-up', '100', '110', '120', '130', '135', '136', 'S 100', 'MB', 'Tudor', 'Popular', 'Octavia (1959)', '1000 MB', 'S 110 R', 'Rapid (1984)', 'Favorit (1987)', 'Epiq', 'Elroq', 'Slavia', 'Kushaq', 'Superb (2024)', 'Kodiaq RS', 'Octavia RS'] },
  { make: "Smart", models: ['Smart Fortwo', 'Smart Forfour', 'Smart Roadster', 'Smart Crossblade', 'Smart City Coupe', 'Smart EQ Fortwo', 'Smart EQ Forfour', 'Smart #1', 'Smart #3', 'Smart #5', 'Smart K', 'Smart Formore (cancelled)', 'Smart Fortwo Brabus', 'Smart Fortwo Electric Drive'] },
  { make: "Subaru", models: ['Impreza', 'WRX', 'WRX STI', 'Legacy', 'Outback', 'Forester', 'Crosstrek', 'XV', 'Baja', 'SVX', 'XT', 'Alcyone', 'Justy', 'Loyale', 'GL', 'DL', 'Leone', 'Tribeca', 'Ascent', 'Solterra', 'Brat', 'BRZ', 'BRAT', '360', 'Sambar', 'Domingo', 'Rex', 'Vivio', 'Pleo', 'Stella', 'R2', 'Lucra', 'Dex', 'Traviq', 'Forester Wilderness', 'Outback Wilderness', 'Crosstrek Wilderness', 'Levorg', 'WRX VB', 'Impreza WRX', '22B STI', 'S209', 'B9 Tribeca', 'Solterra (2023)'] },
  { make: "Suzuki", models: ['Swift', 'Vitara', 'Grand Vitara', 'Jimny', 'Samurai', 'SJ410', 'SJ413', 'Ignis', 'Splash', 'Wagon R', 'Alto', 'Celerio', 'Baleno', 'SX4', 'S-Cross', 'Liana', 'Esteem', 'Cultus', 'Every', 'Carry', 'Super Carry', 'XL-7', 'XL6', 'Ertiga', 'Xbee', 'Across', 'Swace', 'Fronx', 'Brezza', 'Dzire', 'A-Star', 'Kei', 'Cappuccino', 'Twin', 'Sidekick', 'Forenza', 'Reno', 'Verona', 'Aerio', 'Kizashi', 'Wagon R (India)', 'Alto 800', 'S-Presso', 'Jimny 5-Door', 'Swift Sport', 'Baleno RS', 'Vitara Brezza', 'Invicto'] },
  { make: "Tata", models: ['Indica', 'Indigo', 'Nano', 'Safari', 'Sumo', 'Sumo Grande', 'Aria', 'Vista', 'Manza', 'Nexon', 'Harrier', 'Safari (2021)', 'Altroz', 'Tiago', 'Tigor', 'Punch', 'Curvv', 'Curvv EV', 'Avinya', 'Sierra EV', 'Harrier EV', 'Xenon', 'Ace', 'Magic', 'Winger', 'Yodha', 'Zest', 'Bolt', 'Sierra (1991)', 'Estate', 'Tata Sierra EV (2025)', 'Nexon EV', 'Tiago EV', 'Tigor EV', 'Punch EV', 'Altroz Racer'] },
  { make: "Tesla", models: ['Roadster', 'Model S', 'Model 3', 'Model X', 'Model Y', 'Cybertruck', 'Semi', 'Roadster (2026)', 'Cybertruck (2024)', 'Model S Plaid', 'Model 3 Performance', 'Model X Plaid', 'Model Y Performance', 'Model S (2021 Refresh)', 'Model 3 (2024 Highland)'] },
  { make: "Toyota", models: ['Camry', 'Corolla', 'Altis', 'Yaris', 'Vios', 'Avalon', 'Crown', 'Crown Majesta', 'Celica', 'Supra', 'GR Supra', 'MR2', 'MR-S', '2000GT', 'GR86', '86/GT86', 'RAV4', 'Highlander', 'Kluger', '4Runner', 'Land Cruiser', 'Land Cruiser Prado', 'FJ Cruiser', 'Sequoia', 'Tundra', 'Tacoma', 'Hilux', 'Hilux Surf', 'T100', 'Sienna', 'Previa', 'Estima', 'Alphard', 'Vellfire', 'Hiace', 'Coaster', 'Dyna', 'Prius', 'Prius Prime', 'Prius c', 'Prius v', 'bZ4X', 'Mirai', 'Aqua', 'Passo', 'Vitz', 'C-HR', 'C-HR+', 'Corolla Cross', 'Urban Cruiser', 'Belta', 'Allion', 'Premio', 'Mark X', 'Mark II', 'Chaser', 'Cresta', 'Soarer', 'Lexus SC (rebadge)', 'Corona', 'Carina', 'Corona EXiV', 'Starlet', 'Tercel', 'Paseo', 'Cynos', 'Echo', 'Aygo', 'Aygo X', 'iQ', 'Scion xA', 'Scion xB', 'Scion tC', 'Scion FR-S', 'GR Yaris', 'GR Corolla', 'GR H2 Racing', 'Century', 'Century SUV', 'Comfort', 'Crown Crossover', 'Crown Sport', 'Crown Sedan', 'Crown Signia', 'Sports 800', 'Publica', 'Mega Cruiser'] },
  { make: "Triumph", models: ['TR2', 'TR3', 'TR3A', 'TR4', 'TR4A', 'TR5', 'TR6', 'TR7', 'TR8', 'Spitfire', 'GT6', 'Herald', 'Vitesse', 'Toledo', 'Dolomite', 'Acclaim', 'Stag', '2000', '2500', '1300', '1500', 'Mayflower', 'Renown', 'Roadster', 'Southern Cross', 'TR250', 'TR3B', 'Italia', '12/50'] },
  { make: "Vauxhall", models: ['Viva', 'Victor', 'Velox', 'Cresta', 'Cavalier', 'Carlton', 'Senator', 'Astra', 'Vectra', 'Omega', 'Nova', 'Corsa', 'Calibra', 'Frontera', 'Sintra', 'Zafira', 'Meriva', 'Agila', 'Signum', 'Insignia', 'Adam', 'Mokka', 'Crossland', 'Grandland', 'Combo', 'Vivaro', 'Movano', 'Ampera', 'Ampera-e', 'Mokka-e', 'Corsa-e', 'Vivaro-e', 'Combo-e', 'Cascada', 'GT', 'Lotus Carlton', 'Chevette', 'Bedford (commercial)', '10-4', '12-4', '14-6', 'Wyvern', 'Rekord (badge engineered)', 'Kadett (rebadged)', 'Frontera (2024)', 'Grandland (2024)'] },
  { make: "Volkswagen", models: ['Beetle', 'Golf', 'Jetta', 'Passat', 'Polo', 'Lupo', 'Fox', 'Up!', 'e-Up!', 'ID.3', 'ID.4', 'ID.5', 'ID.6', 'ID.7', 'ID.Buzz', 'ID.2all', 'T-Cross', 'T-Roc', 'Taigo', 'Tiguan', 'Tayron', 'Touareg', 'Atlas', 'Atlas Cross Sport', 'Teramont', 'Käfer', 'Bus', 'Transporter', 'Multivan', 'Caravelle', 'California', 'Crafter', 'LT', 'Lupo GTI', 'Golf GTI', 'Golf R', 'Golf GTD', 'Polo GTI', 'Jetta GLI', 'Scirocco', 'Corrado', 'Karmann Ghia', 'Type 3', 'Type 4', '411', '412', 'Phaeton', 'Arteon', 'CC', 'Eos', 'New Beetle', 'Beetle (A5)', 'Bora', 'Santana', 'Vento', 'Caddy', 'Saveiro', 'Amarok', 'Nivus', 'Taos', 'Virtus', 'Lamando', 'Magotan', 'Lavida', 'Sagitar', 'Passat CC', 'W12', 'Nardo', 'W12 Coupe', 'XL1', 'L1', 'Concept R', 'ID.GTI', 'ID. Buzz Cargo', 'Golf R 333', 'Golf Clubsport', 'Touareg R', 'Arteon R'] },
  { make: "Volvo", models: ['PV444', 'PV544', 'Amazon', 'P1800', 'P1800ES', '140 Series', '164', '240 Series', '260 Series', '340', '360', '440', '460', '480', '740', '760', '780', '850', '940', '960', 'S40', 'S60', 'S70', 'S80', 'S90', 'V40', 'V50', 'V60', 'V70', 'V90', 'C30', 'C70', 'XC60', 'XC70', 'XC90', 'XC40', 'EX30', 'EX90', 'EC40', 'EM90', 'ES90', 'EX30 Cross Country', 'P1800 Cyan', 'Polestar 1 (shared)', '242 GT', '245 GL', '850 T-5R', '850 R', 'V70 R', 'S60 Polestar', 'XC90 Recharge', 'S60 T8 Polestar', 'V60 Polestar', 'V90 Cross Country', 'S90 Recharge', 'XC60 Recharge', 'Duett', 'S80 V8', '240 Turbo', '780 Bertone', '262C Bertone', 'Amazon Estate', 'PV831', 'FP'] },
];
